[2024-11-25T20:25:06.062+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: kafka_to_snowflake_pipeline.start_kafka_consumer manual__2024-11-25T20:24:55.365156+00:00 [queued]>
[2024-11-25T20:25:06.068+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: kafka_to_snowflake_pipeline.start_kafka_consumer manual__2024-11-25T20:24:55.365156+00:00 [queued]>
[2024-11-25T20:25:06.069+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-11-25T20:25:06.069+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-11-25T20:25:06.069+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-11-25T20:25:06.077+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): start_kafka_consumer> on 2024-11-25 20:24:55.365156+00:00
[2024-11-25T20:25:06.098+0000] {standard_task_runner.py:55} INFO - Started process 323 to run task
[2024-11-25T20:25:06.109+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_to_snowflake_pipeline', 'start_kafka_consumer', 'manual__2024-11-25T20:24:55.365156+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_snowflake_etl_dag.py', '--cfg-path', '/tmp/tmpholiahke']
[2024-11-25T20:25:06.115+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask start_kafka_consumer
[2024-11-25T20:25:06.156+0000] {task_command.py:389} INFO - Running <TaskInstance: kafka_to_snowflake_pipeline.start_kafka_consumer manual__2024-11-25T20:24:55.365156+00:00 [running]> on host f25f59e56f04
[2024-11-25T20:25:06.370+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Vaibhav Bansal
AIRFLOW_CTX_DAG_ID=kafka_to_snowflake_pipeline
AIRFLOW_CTX_TASK_ID=start_kafka_consumer
AIRFLOW_CTX_EXECUTION_DATE=2024-11-25T20:24:55.365156+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-11-25T20:24:55.365156+00:00
[2024-11-25T20:25:06.406+0000] {kafka_to_snowflake_etl_dag.py:211} ERROR - Kafka Consumer failed with error: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2024-11-25T20:25:06.407+0000] {python.py:177} INFO - Done. Returned value was: False
[2024-11-25T20:25:06.471+0000] {taskinstance.py:1322} INFO - Marking task as SUCCESS. dag_id=kafka_to_snowflake_pipeline, task_id=start_kafka_consumer, execution_date=20241125T202455, start_date=20241125T202506, end_date=20241125T202506
[2024-11-25T20:25:06.493+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-11-25T20:25:06.515+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
